language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
- '4.0'
- '5.0'
after_script: npm install codecov.io && cat ./coverage/lcov.info | codecov
sudo: false
deploy:
  provider: npm
  email: tituswormer@gmail.com
  api_key:
    secure: AYEUdOYZcalRsKXdagnHSUK/QgLZVgO3ZUjaK6Uy7eIsiz8hd6k9t+QGD1toXcRIL86z6+PX4RS+5EyRb4E42acclg55EqlpdxTCtfM9+n2zhDFNcB3+SuHZYeY83PfxtgqipdQds6xqpDwmlLZTBgcLgxVsC2lc70rCXrM9Dd8=
  on:
    repo: wooorm/trigrams
